apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: d08bdaf4-4c08-4d1b-8591-1549300fb39c
    keyvaultName: django-api-secretkey
    cloudName: ""
    objects: |
      array:
        - |
          objectName: django-key
          objectType: secret
    tenantId: eb9b34bc-dedb-4667-9285-7868247187e6
  secretObjects:
    - secretName: django-secret
      type: Opaque
      data:
        - key: django-key
          objectName: django-key
